spring:
  application:
    name: Project X
  #  resources:
  #    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # Optional: Disable template caching in dev mode
  liquibase:
    enabled: true
    change-log: db/db.changelog-master.yml
    drop-first: true
  datasource:
    url: jdbc:postgresql://localhost:5432/project_x
    username: postgres
    password: StiffMedal30  # Use an environment variable for sensitive data
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: your_jwt_secret
      expiration: 86400000  # 1 day in milliseconds
  web:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: true
  management:
    endpoints:
      web:
        base-path: /actuator
        exposure:
          include: "*"
      health:
        enabled: true
        show-details: always
      mappings:
        enabled: true
        show-details: always
      info:
        enabled: true
        show-details: always
  logging:
    level:
      org:
        springframework:
          web: TRACE
          boot:
            actuate: TRACE

server:
  port: 8080