spring:
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml
  application:
    name:Project X
  datasource:
    url: jdbc:postgresql://localhost:5432/project_x
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000  # 1 day in milliseconds

server:
  port: 8080